version: "3"

services:
  localstack:
    image: localstack/localstack:0.12.9
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8010}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker-reuse
      - KINESIS_ERROR_PROBABILITY=0.01
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-southeast-1
    volumes:
      - my-datavolume:/tmp/localstack

  redis-master:
    container_name: redis-master
    restart: always
    image: redis
    volumes:
      - my-datavolume:/data
    ports:
      - 6379:6379

  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb
    restart: always
    ports:
      - 8020:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566

volumes:
  my-datavolume:
